services:

  squeak:
    build:
      context: .
      dockerfile: Dockerfile.squeak
    container_name: kethernet-squeak
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./kethernet:/kethernet:ro
      - navi-data:/navi:rw
    stdin_open: true
    tty: true
    networks:
      - kethernet

  pharo:
    build:
      context: .
      dockerfile: Dockerfile.pharo
    container_name: kethernet-pharo
    stdin_open: true
    tty: true
    volumes:
      - ./smalltalk:/smalltalk:ro
      - navi-data:/navi:rw
    networks:
      - kethernet

networks:
  kethernet:
    driver: bridge

volumes:
  navi-data: